#!/bin/sh
 
### BEGIN INIT INFO
# Provides: fc
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts the PSAS flight computer
# Description: Starts the PSAS flight computer
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/root/av3-fc/fc"
NAME=fc
DESC=fc
PROJECTPATH="/root/logs/"

start_service () {
	mkdir -p /var/run/$NAME
	echo "Starting PSAS FC service"
	start-stop-daemon --start --background --nicelevel -19 --make-pidfile --pidfile /var/run/$NAME/$NAME.pid --chdir $PROJECTPATH --exec $DAEMON 
}

stop_service () {
	echo "stopping PSAS FC service"
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME/$NAME.pid
}

case "$1" in
'start')
  start_service
  ;;
'stop')
  stop_service
  ;;
'restart')
  stop_service
  start_service
  ;;
*)
  echo "Usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
